version: "3.9"

services:
  testing-in-ubuntu:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu.dockerfile
    container_name: local-sherpa-ubuntu
    volumes:
      - .:/app
    stdin_open: true
    tty: true
